-- SELECT, UPDATE SET, INSERT INTO, DELETE, WHERE, GROUP, HAVING, JOIN 

-- STUDENT
-- 각 학과의 가장 키가 큰 사람을  구해라 - 학번, 이름, 키
SELECT STU_DEPT, MAX(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

SELECT S.STU_NO, STU_NAME, STU_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, MAX(STU_HEIGHT) MAX_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT AND S.STU_HEIGHT = T.MAX_HEIGHT;

-- 1. 각 직급별 가장 많은 급여를 받는 교수의 이름,급여 출력 (PROFESSOR)
SELECT P.POSITION, NAME, P.PAY
FROM PROFESSOR P
INNER JOIN (
    SELECT POSITION, MAX(PAY) MAX_PAY
    FROM PROFESSOR
    GROUP BY POSITION
) A ON P.POSITION = A.POSITION AND P.PAY = A.MAX_PAY;

-- 2. 본인 부서의 평균 급여보다 높은 급여를 받는 사원의 사번, 이름, 급여 출력 (EMP)
SELECT EMPNO, ENAME, SAL
FROM EMP E
INNER JOIN (
    SELECT DEPTNO, ROUND(AVG(SAL)) AVG_SAL
    FROM EMP
    GROUP BY DEPTNO
) B ON E.DEPTNO = B.DEPTNO AND E.SAL > B.AVG_SAL;