-- 1. ALLEN과 같은 JOB, DEPTNO(부서)를 가진 사람을 구하시오.(ENAME, DNAME 출력)
-- (ALLEN은 출력하지 말 것)

SELECT *
FROM EMP E
INNER JOIN (
    SELECT *
    FROM EMP
    WHERE ENAME = 'ALLEN'
) T ON E.JOB = T.JOB AND E.DEPTNO = T.DEPTNO
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
