-- 1. 성이 '김'씨인 학생들의 학번, 이름, 학과를 출력하시오.
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE STU_NAME LIKE '%김%'; -- SUBSTR(STU_NAME, 1,1) = '김';

-- 2. 15학번 학생들의 학번, 이름, 학과를 출력하시오.
SELECT STU_NO, STU_NAME, STU_DEPT
FROM STUDENT
WHERE SUBSTR(STU_NO, 3, 2) = 15;

-- 3. 컴퓨터정보 학과 학생들의 시험 평균 점수를 구하시오.
SELECT STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT
HAVING STU_DEPT = '컴퓨터정보';

-- 4. 컴퓨터개론 수업을 듣는 학생의 학번, 이름, 학과, 시험점수를 구하시오.
SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB.SUB_NAME = '컴퓨터개론';

-- 5. 학생들의 전체 평균 키보다 큰 키를 가진 학생들의 학번, 이름, 키를 출력하시오.
SELECT STU_NO, STU_NAME, STU_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT AVG(STU_HEIGHT) AVG_HEIGHT
    FROM STUDENT
) T ON S.STU_HEIGHT > T.AVG_HEIGHT;

-- 6. 본인 학과의 평균 키보다 큰 학생들의 이름, 학과, 키, 학과 평균키 값 출력
SELECT STU_NAME, S.STU_DEPT, STU_HEIGHT, T.AVG_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, AVG(STU_HEIGHT) AVG_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_HEIGHT > T.AVG_HEIGHT AND S.STU_DEPT = T.STU_DEPT;