-- 1. 남자이면서(주민번호 7번째자리 1) 공과대학에 속한 학생의 수를 구하시오.
SELECT COUNT(DECODE(SUBSTR(JUMIN, 7, 1), 1, '남자')) 공과대학남자수
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '공과대학';

-- 2. 학생들의 아이디의 마지막 세글자를 '*' 로 채우시오
SELECT RPAD(SUBSTR(ID, 1, LENGTH(ID)-3), LENGTH(ID), '*')
FROM STU;

-- 3. 보너스+급여가 400 이하인 교수들의 이름, 아이디, 학과명을 출력하시오.
SELECT NAME, ID, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO
WHERE BONUS+PAY <= 400; -- NVL(BONUS,0) => NULL을 0으로 대체해주는 함수

-- 4. 담당 학생이 2명이상인 교수의 이름, 아이디, 담당학생 수를 출력하시오.
SELECT P.NAME, P.ID, COUNT(*)
FROM PROFESSOR P
INNER JOIN STU S ON S.PROFNO = P.PROFNO -- PROFNO = 담당교수번호
GROUP BY P.NAME, P.ID
HAVING COUNT(*) >= 2;

-- 5. 가장 높은 급여를 받는 교수의 학과에 해당하는 학생 수 출력
SELECT COUNT(*) 학과학생수
FROM PROFESSOR P
INNER JOIN (
    SELECT MAX(PAY) MAX_PAY
    FROM PROFESSOR
) T ON P.PAY = T.MAX_PAY
INNER JOIN STU S1 ON P.DEPTNO = S1.DEPTNO1;