-- 그룹 함수
-- SUM, AVG, MAX, MIN, COUNT

SELECT POSITION, SUM(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT * FROM STU; -- 학년별로 평균 몸무게

SELECT GRADE, AVG(WEIGHT)
FROM STU
GROUP BY GRADE;

SELECT COUNT(*)
FROM STUDENT;

SELECT COUNT(BONUS) -- BONUS가 NULL이 아닌 레코드의 수
FROM PROFESSOR;

-- STUDENT 테이블에서 각 학과의 학생수
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT
HAVING COUNT(*) >= 4;

-- STEP 1. 각 학과별 학생 수
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT;

-- STEP 2. 각 학과별 남자 학생 수
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT;

-- STEP 3. 각 학과에서 남자가 2명이상인 학과명, 학생 수 출력
SELECT STU_DEPT, COUNT(*)
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT
HAVING COUNT(*) >= 2;