SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

-- 사용자별 글 개수 
-- 출력 컬럼 = 닉네임,글 개수

SELECT NICKNAME, COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NICKNAME;

SELECT NICKNAME, TITLE
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

---------------------------

-- 1)각 게시글의 제목, 댓글 개수 출력
-- + 게시글에 댓글이 없는 경우 개수를 0으로 출력
SELECT B.BOARDNO, TITLE, COUNT(C.BOARDNO) 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY TITLE, B.BOARDNO; -- <= TITLE은 PK가 아니어서 동일한 제목 글이 묶일수도 있어서 PK값인 BOARDNO로도 묶어야한다

SELECT *
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO;

----------------------------------------------

-- 게시글 번호, 게시글 제목, 내용, 작성일,  작성자 닉네임, 댓글 개수(없으면0) 출력

SELECT B.BOARDNO, TITLE, B.CONTENTS, B.CDATETIME, NICKNAME, COUNT(COMMENTNO) 댓글개수
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY TITLE, B.BOARDNO, B.CONTENTS, B.CDATETIME, NICKNAME
ORDER BY B.BOARDNO; -- 컬럼이 많아지면 GROUP의 수가 계속 늘어나기에 비효율적

SELECT B.BOARDNO, COUNT(C.BOARDNO) 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO; -- <= 결과로 나온 테이블을 JOIN으로 서브쿼리로 만들어서 넣기

SELECT B.BOARDNO, TITLE, CONTENTS, B.CDATETIME, NICKNAME, 댓글개수
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
INNER JOIN (
    SELECT B.BOARDNO, COUNT(C.BOARDNO) 댓글개수
    FROM TBL_BOARD B
    LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO
)T ON B.BOARDNO = T.BOARDNO;

-------------------------

-- CASE ~ WHEN
-- PROFESSOR
-- 1. PROFESSOR 테이블에서 400이상의 급여를 받으면 A,
--    300~400 사이면 B, 나머지는 C로 출력
--    교수이름, 급여 등급(A~C)

SELECT *
FROM PROFESSOR;

SELECT NAME, PAY,
    CASE
        WHEN PAY >= 400 THEN 'A'
        WHEN PAY >= 300 THEN 'B'
        ELSE 'C'
    END
FROM PROFESSOR; --CASE, WHEN, THEN, END






