SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

SELECT * 
FROM TBL_BOARD;

-- 각 유저가 작성한 게시글의 수(출력 컬럼 : 유저 아이디, 이름, 게시글 개수)

SELECT B.USERID, NAME, COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NAME;

SELECT U.USERID, NAME, COUNT(BOARDNO) CNT
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON B.USERID = U.USERID
GROUP BY U.USERID, NAME;

---------------------------------------------------

-- 각 유저가 작성한 댓글의 수(출력 컬럼 : 유저 아이디, 이름, 댓글 개수)

SELECT U.USERID, NAME, COUNT(*) 댓글개수
FROM TBL_USER U
INNER JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY U.USERID, NAME;

SELECT U.USERID, NAME, COUNT(COMMENTNO) 댓글개수
FROM TBL_USER U
LEFT JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY U.USERID, NAME;

----------------------------------------------

-- TBL_USER, TBL_BOARD, TBL_COMMENT

-- 1. 아이디에 user가 들어가는 사람이 작성한 게시글의 수를 구하시오.

SELECT B.USERID, COUNT(*)
FROM TBL_BOARD B
INNER JOIN (
    SELECT *
    FROM TBL_USER
    WHERE USERID LIKE '%user%'
) T ON B.USERID = T.USERID
GROUP BY B.USERID;

-- 2. USER의 핸드폰 번호 가운데를 *로 처리하시오.
-- (ex, 010-****-5678)

SELECT RPAD(SUBSTR(PHONE, 1, 4), LENGTH(PHONE)-5, '*') || SUBSTR(PHONE, INSTR(PHONE, '-')+5, LENGTH(PHONE)) PHONE
FROM TBL_USER;

-- 3. 게시글에 좋아요 개수가 가장 큰 게시글을 작성한 사람의 아이디, 이름, 좋아요개수를 출력하시오.

SELECT B.USERID, NAME, B.FAVORITE
FROM TBL_BOARD B
INNER JOIN (
    SELECT MAX(FAVORITE) FAVORITE
    FROM TBL_BOARD
) T ON B.FAVORITE = T.FAVORITE
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

-- 4. 게시글 번호, 제목, 내용, 게시글 작성자 닉네임, 댓글 수(없으면 0)를 출력하시오.

SELECT B.BOARDNO, B.TITLE, B.CONTENTS, NICKNAME, COUNT(COMMENTNO) 댓글수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON C.BOARDNO = B.BOARDNO
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.BOARDNO, B.TITLE, B.CONTENTS, NICKNAME;
    
-- 5. 조회수가 가장 큰 게시글의 게시글 번호, 제목, 작성자 닉네임을 출력하시오.

SELECT BOARDNO, TITLE, NICKNAME
FROM TBL_BOARD B
INNER JOIN (
    SELECT MAX(CNT) CNT
    FROM TBL_BOARD
) T ON B.CNT = T.CNT
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

