-- 1. '컴퓨터정보' 학과에 속한 학생들의 학번, 이름, 평균시험점수를 출력하시오
-- (STUDENT, ENROL)
SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE STU_DEPT = '컴퓨터정보'
GROUP BY STU_NAME, S.STU_NO;

-- 2. '강종영' 교수의 과목 시험을 본 학생의 학번, 이름, 점수, 과목명을 출력하시오.
-- (STUDENT, ENROL, SUBJECT)
SELECT S.STU_NO, STU_NAME, ENR_GRADE, SUB.SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB.SUB_NO = 101;

-- 3. 학생들의 이름, 시험을 본 개수를 출력하시오. 
-- 시험을 안본 사람은 출력을 안하거나 0으로 출력하거나 상관없음.
-- (STUDENT, ENROL)
SELECT S.STU_NAME, COUNT(*) 시험개수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;

-- 4. 모든 학생들의 시험 평균 점수보다 높은 평균점수를 가지는 학생들의 학번, 이름, 평균점수를 출력하시오.
-- (STUDENT, ENROL)
SELECT STU_NAME, S.STU_NO, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE ENR_GRADE > (
    SELECT AVG(ENR_GRADE)
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
)
GROUP BY STU_NAME, S.STU_NO;

-------------------------

-- 5. 사원번호, 이름, 급여 등급, 사수(MANAGER)이름을 출력하시오.
-- (EMP, SALGRADE)
SELECT E1.EMPNO, E1.ENAME, S.GRADE, E2.ENAME 사수
FROM EMP E1
INNER JOIN SALGRADE S ON E1.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

-- 6. 부서별 급여의 평균 등급을 출력하시오. - 부서명, 급여 평균 등급 출력
-- (EMP, SALGRADE, DEPT)
SELECT D.DNAME, ROUND(AVG(GRADE), 2)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME;

-- 7. 인문대학에 속한 교수의 이름을 모두 출력하시오.
-- (PROFESSOR, DEPARTMENT)
SELECT P.NAME, D3.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART
INNER JOIN PROFESSOR P ON P.DEPTNO = D3.DEPTNO
WHERE D1.DNAME = '인문대학';